- name: Install aptitude
  apt:
    name: aptitude
    state: latest
    update_cache: true

- name: Add Jenkins apt Key
  apt_key:
    url: "{{ jenkins_key }}"
    state: present

- name: Add Jenkins Repository
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present

- name: Update apt 
  apt:
    update_cache: true

- name: Install java
  apt: 
   name: "{{ java_version }}"
   state: present

- name: Install jenkins
  apt:
   name: jenkins
   state: present

- name: Stop jenkins
  service:
    name: jenkins.service
    state: stopped

- name: Shell 1
  shell:
    "sudo rm -rf /var/lib/jenkins"

- name: Shell 2
  shell:
    "wget --load-cookies /tmp/cookies.txt "https://docs.google.com/uc?export=download&confirm=$(wget --quiet --save-cookies /tmp/cookies.txt --keep-session-cookies --no-check-certificate 'https://docs.google.com/uc?export=download&id=1foQ6K9VtCZGAP39FrG3-0JGEJYYcCzPh' -O- | sed -rn 's/.*confirm=([0-9A-Za-z_]+).*/\1\n/p')&id=1foQ6K9VtCZGAP39FrG3-0JGEJYYcCzPh" -O jenkins.tar.gz && rm -rf /tmp/cookies.txt /root/jenkins.tar.gz"

- name: Shell 3
  shell:
    "sudo chown -R jenkins:jenkins /root"

- name: Shell  4
  shell:
    "sudo tar zxvf /root/jenkins.tar.gz"

- name: Shell  5
  shell:
    "sudo mv /root/jenkins root/var/lib/"

- name: Start jenkins
  service:
    name: jenkins.service
    state: restarted
    enabled: yes
    daemon_reload: true
