---
- name: Playbook for diplom - infrastructure
  hosts: prod
  become: true
  roles:
    - docker 
    - jenkins
    - grafana
    - prometheus  
    - prom_docker_export 
    - cadvisor
    - alertmanager
    - blackbox
